import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Check, Pencil, UserRound, UserX } from "lucide-react";
import { Button } from "@/components/ui/button";
import { listAuthorizedPeople, listSectorsForAuthorization, saveAuthorizedPerson, setAuthorizedPersonActive } from "@/lib/foundation.functions";
type Role = "admin" | "direcao" | "responsavel" | "colaborador";
type Person = { id:string; email:string; nome:string; papel:Role; setores:string[]; ativo:boolean; registered:boolean; user_id:string|null };
type Sector = { id:string; name:string; active:boolean };
const roles = [{value:"admin",label:"Administrador"},{value:"direcao",label:"Direção"},{value:"responsavel",label:"Responsável de setor"},{value:"colaborador",label:"Colaborador"}] as const;
export const Route = createFileRoute("/_authenticated/admin/pessoas")({ head:()=>({meta:[{title:"Pessoas autorizadas — RS CONECT"}]}), component:PeopleAdminPage });
function PeopleAdminPage() {
 const qc=useQueryClient(); const listFn=useServerFn(listAuthorizedPeople); const sectorsFn=useServerFn(listSectorsForAuthorization); const saveFn=useServerFn(saveAuthorizedPerson); const activeFn=useServerFn(setAuthorizedPersonActive);
 const {data:people=[],isLoading,error}=useQuery({queryKey:["authorized-people"],queryFn:()=>listFn()}); const {data:sectors=[]}=useQuery({queryKey:["authorization-sectors"],queryFn:()=>sectorsFn()});
 const [editing,setEditing]=useState<Person|null>(null); const [email,setEmail]=useState(""); const [nome,setNome]=useState(""); const [papel,setPapel]=useState<Role>("colaborador"); const [setores,setSetores]=useState<string[]>([]); const [ativo,setAtivo]=useState(true); const [feedback,setFeedback]=useState(""); const [failure,setFailure]=useState("");
 function reset(){setEditing(null);setEmail("");setNome("");setPapel("colaborador");setSetores([]);setAtivo(true);}
 function edit(p:Person){setEditing(p);setEmail(p.email);setNome(p.nome);setPapel(p.papel);setSetores(p.setores??[]);setAtivo(p.ativo);setFeedback("");setFailure("");}
 const save=useMutation({mutationFn:()=>saveFn({data:{id:editing?.id,email,nome,papel,setores,ativo}}),onSuccess:async()=>{setFeedback("Pessoa salva.");setFailure("");reset();await qc.invalidateQueries({queryKey:["authorized-people"]});},onError:(e)=>setFailure(e instanceof Error?e.message:"Não foi possível salvar.")});
 const toggle=useMutation({mutationFn:(p:Person)=>activeFn({data:{id:p.id,ativo:!p.ativo}}),onSuccess:async()=>{await qc.invalidateQueries({queryKey:["authorized-people"]});},onError:(e)=>setFailure(e instanceof Error?e.message:"Não foi possível alterar o acesso.")});
 return <div className="space-y-6">
 <header><p className="text-xs font-bold uppercase tracking-wider text-primary">Administração</p><h1 className="mt-1 text-2xl font-black">Pessoas autorizadas</h1><p className="mt-1 text-sm text-muted-foreground">Somente e-mails autorizados podem criar uma conta.</p></header>
 <section className="rounded-2xl border bg-card p-4 sm:p-6"><div className="mb-4 flex items-center gap-2"><UserRound className="size-5 text-primary"/><h2 className="font-bold">{editing?"Editar pessoa":"Adicionar pessoa"}</h2></div>
 <form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();setFailure("");save.mutate();}}>
 <label className="space-y-1.5 text-sm font-medium">E-mail<input className="h-10 w-full rounded-lg border bg-background px-3 disabled:opacity-60" type="email" required value={email} disabled={!!editing?.registered} onChange={e=>setEmail(e.target.value)}/>{editing?.registered?<span className="block text-xs text-muted-foreground">O e-mail de uma conta criada é gerenciado pelo provedor.</span>:null}</label>
 <label className="space-y-1.5 text-sm font-medium">Nome completo<input className="h-10 w-full rounded-lg border bg-background px-3" required minLength={2} maxLength={120} value={nome} onChange={e=>setNome(e.target.value)}/></label>
 <label className="space-y-1.5 text-sm font-medium">Papel<select className="h-10 w-full rounded-lg border bg-background px-3" value={papel} onChange={e=>setPapel(e.target.value as Role)}>{roles.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select></label>
 <label className="flex items-center gap-2 self-end pb-2 text-sm font-medium"><input type="checkbox" checked={ativo} onChange={e=>setAtivo(e.target.checked)}/> Acesso ativo</label>
 <fieldset className="sm:col-span-2"><legend className="mb-2 text-sm font-semibold">Setores autorizados</legend><p className="mb-3 text-xs text-muted-foreground">Os setores serão atribuídos no cadastro e sincronizados em contas existentes.</p><div className="grid gap-2 sm:grid-cols-2">{(sectors as Sector[]).filter(s=>s.active).map(s=><label key={s.id} className="flex items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={setores.includes(s.id)} onChange={e=>setSetores(e.target.checked?[...setores,s.id]:setores.filter(id=>id!==s.id))}/>{s.name}</label>)}</div></fieldset>
 {failure?<p role="alert" className="sm:col-span-2 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{failure}</p>:null}{feedback?<p role="status" className="sm:col-span-2 text-sm text-emerald-700">{feedback}</p>:null}
 <div className="flex gap-2 sm:col-span-2"><Button type="submit" disabled={save.isPending}><Check className="size-4"/>{save.isPending?"Salvando…":"Salvar pessoa"}</Button>{editing?<Button type="button" variant="outline" onClick={()=>{reset();setFeedback("");setFailure("");}}>Cancelar</Button>:null}</div>
 </form></section>
 <section className="space-y-3"><div className="flex items-end justify-between"><h2 className="text-lg font-bold">Lista de acesso</h2><span className="text-sm text-muted-foreground">{people.length} pessoa(s)</span></div>{error?<p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">Não foi possível carregar a lista. Verifique suas permissões.</p>:null}{isLoading?<p className="text-sm text-muted-foreground">Carregando…</p>:people.map((p:Person)=><article key={p.id} className="rounded-2xl border bg-card p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{p.nome}</h3><span className={"rounded-full px-2 py-0.5 text-xs font-semibold "+(p.ativo?"bg-emerald-500/10 text-emerald-700":"bg-muted text-muted-foreground")}>{p.ativo?"Ativo":"Desativado"}</span>{p.registered?<span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs font-semibold text-primary">Conta criada</span>:null}</div><p className="mt-1 break-all text-sm text-muted-foreground">{p.email}</p><p className="mt-2 text-sm">{roles.find(r=>r.value===p.papel)?.label??p.papel}</p><p className="mt-1 text-xs text-muted-foreground">{(p.setores??[]).length? p.setores.length+" setor(es) atribuído(s)":"Sem setores atribuídos"}</p></div><div className="flex shrink-0 gap-2"><Button variant="outline" size="sm" onClick={()=>edit(p)}><Pencil className="size-4"/>Editar</Button><Button variant="outline" size="sm" disabled={toggle.isPending} onClick={()=>toggle.mutate(p)}><UserX className="size-4"/>{p.ativo?"Desativar":"Reativar"}</Button></div></div></article>)}</section>
 </div>;
}