import { type FormEvent, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { CalendarDays, ChevronLeft, ChevronRight, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { getSession } from "@/lib/session.functions";

type Category = "espaco"|"equipamento";
type Resource = {id:string;nome:string;categoria:Category;ativo:boolean};
type Reservation = {id:string;recurso_id:string;created_by:string;inicio:string;fim:string;finalidade:string;status:"ativa"|"cancelada";created_at:string;reservante_nome:string};

const categoryLabel=(c:Category)=>c==="espaco"?"Espaço":"Equipamento";
const fmtTime=(v:string)=>new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit",timeZone:"America/Sao_Paulo"}).format(new Date(v));
const fmtDate=(v:string)=>new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",timeZone:"America/Sao_Paulo"}).format(new Date(v));
const isoLocal=(date:string,time:string)=>date+"T"+time+":00-03:00";
const addDays=(s:string,n:number)=>{const d=new Date(s+"T12:00:00-03:00");d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const weekStart=(s:string)=>{const d=new Date(s+"T12:00:00-03:00");const day=d.getUTCDay();return addDays(s,-(day===0?6:day-1));};
const daysOfWeek=(s:string)=>Array.from({length:7},(_,i)=>addDays(s,i));
const rangesOverlap=(r:Reservation,a:string,b:string)=>new Date(r.inicio)<new Date(b)&&new Date(r.fim)>new Date(a);

export const Route=createFileRoute("/_authenticated/reservas")({head:()=>({meta:[{title:"Reservas — RS CONECT"}]}),component:ReservasPage});

function ReservasPage(){
 const qc=useQueryClient();const getSessionFn=useServerFn(getSession);
 const {data:session,isLoading:sessionLoading}=useQuery({queryKey:["session"],queryFn:()=>getSessionFn()});
 const isAdmin=!!session?.roles.includes("admin");
 const [selectedDate,setSelectedDate]=useState(()=>new Date().toLocaleDateString("en-CA",{timeZone:"America/Sao_Paulo"}));
 const [view,setView]=useState<"semana"|"dia">("semana");const [creating,setCreating]=useState(false);const [resourceModal,setResourceModal]=useState(false);
 const start=view==="semana"?weekStart(selectedDate):selectedDate;const end=addDays(start,view==="semana"?7:1);
 const {data:resources=[],isLoading:resourcesLoading}=useQuery({queryKey:["reserva-recursos"],queryFn:async()=>{const {data,error}=await supabase.from("recursos_reserva").select("*").order("categoria").order("nome");if(error)throw error;return(data??[]) as Resource[]},enabled:!!session});
 const {data:reservations=[],isLoading:reservationsLoading}=useQuery({queryKey:["reservas",start,end],queryFn:async()=>{const {data,error}=await supabase.rpc("listar_reservas",{_inicio:start+"T00:00:00-03:00",_fim:end+"T00:00:00-03:00"});if(error)throw error;return(data??[]) as Reservation[]},enabled:!!session});
 const mine=(r:Reservation)=>r.created_by===session?.userId;
 async function cancel(id:string){const {error}=await supabase.rpc("cancelar_reserva",{_reserva_id:id});if(error)throw error;await qc.invalidateQueries({queryKey:["reservas"]});}
 if(sessionLoading)return <p className="text-sm text-muted-foreground">Carregando…</p>;
 return <div className="space-y-5">
  <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">Agenda interna</p><h1 className="mt-1 text-2xl font-black">Reservas</h1><p className="mt-1 text-sm text-muted-foreground">Evite conflitos de espaços e equipamentos.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setView(view==="semana"?"dia":"semana")}><CalendarDays className="size-4"/>{view==="semana"?"Visão dia":"Visão semana"}</Button><Button onClick={()=>setCreating(true)}><Plus className="size-4"/>Nova reserva</Button>{isAdmin&&<Button variant="outline" onClick={()=>setResourceModal(true)}><ShieldCheck className="size-4"/>Recursos</Button>}</div></header>
  <div className="flex items-center justify-between rounded-2xl border bg-card p-3"><Button variant="ghost" size="icon" onClick={()=>setSelectedDate(addDays(selectedDate,view==="semana"?-7:-1))}><ChevronLeft className="size-5"/></Button><div className="text-center"><p className="font-bold">{view==="semana"?"Semana de "+fmtDate(start)+" a "+fmtDate(addDays(start,6)):new Intl.DateTimeFormat("pt-BR",{dateStyle:"full",timeZone:"America/Sao_Paulo"}).format(new Date(selectedDate+"T12:00:00-03:00"))}</p><button className="text-xs text-primary" onClick={()=>setSelectedDate(new Date().toLocaleDateString("en-CA",{timeZone:"America/Sao_Paulo"}))}>Hoje</button></div><Button variant="ghost" size="icon" onClick={()=>setSelectedDate(addDays(selectedDate,view==="semana"?7:1))}><ChevronRight className="size-5"/></Button></div>
  {creating?<NewReservation resources={resources.filter(r=>r.ativo)} onClose={()=>setCreating(false)} onSaved={async()=>{setCreating(false);await qc.invalidateQueries({queryKey:["reservas"]});}}/>:null}
  {resourceModal?<ResourceManager resources={resources} onClose={()=>setResourceModal(false)} onChanged={()=>qc.invalidateQueries({queryKey:["reserva-recursos"]})}/>:null}
  {resourcesLoading||reservationsLoading?<p className="text-sm text-muted-foreground">Carregando calendário…</p>:<CalendarView resources={resources} reservations={reservations} start={start} days={view==="semana"?7:1} mine={mine} isAdmin={isAdmin} onCancel={cancel}/>}
  <p className="text-xs text-muted-foreground">Horários em blocos de 30 minutos. A prevenção de conflito é feita no banco de dados.</p>
 </div>;
}

function CalendarView({resources,reservations,start,days,mine,isAdmin,onCancel}:{resources:Resource[];reservations:Reservation[];start:string;days:number;mine:(r:Reservation)=>boolean;isAdmin:boolean;onCancel:(id:string)=>Promise<void>}){
 const dayList=daysOfWeek(start).slice(0,days);
 return <section className="space-y-3">{resources.map(resource=><article key={resource.id} className="overflow-hidden rounded-2xl border bg-card"><div className="flex items-center justify-between border-b px-4 py-3"><div><h2 className="font-bold">{resource.nome}</h2><p className="text-xs text-muted-foreground">{categoryLabel(resource.categoria)} · {resource.ativo?"Ativo":"Inativo"}</p></div><span className="text-xs font-semibold text-muted-foreground">{resource.ativo?"Livre quando não houver reserva":"Inativo"}</span></div><div className={"grid "+(days===7?"grid-cols-7 min-w-[840px]":"grid-cols-1")+" divide-x"}>{dayList.map(day=>{const dayRes=reservations.filter(r=>r.recurso_id===resource.id&&r.status==="ativa"&&rangesOverlap(r,day+"T00:00:00-03:00",addDays(day,1)+"T00:00:00-03:00"));return <div key={day} className="min-h-28 p-2"><p className="text-[11px] font-bold text-muted-foreground">{new Intl.DateTimeFormat("pt-BR",{weekday:"short",day:"2-digit",month:"2-digit",timeZone:"America/Sao_Paulo"}).format(new Date(day+"T12:00:00-03:00"))}</p>{dayRes.length?<div className="mt-2 space-y-1">{dayRes.map(r=><div key={r.id} className="rounded-lg bg-primary/10 p-2 text-xs"><p className="font-bold">{fmtTime(r.inicio)}–{fmtTime(r.fim)}</p><p className="truncate">{r.finalidade}</p><p className="truncate text-muted-foreground">{r.reservante_nome??(mine(r)?"Você":"Reservado")}</p>{(mine(r)||isAdmin)&&<button className="mt-1 inline-flex items-center gap-1 text-destructive" onClick={()=>{if(confirm("Cancelar esta reserva?"))void onCancel(r.id)}}><Trash2 className="size-3"/>Cancelar</button>}</div>)}</div>:<p className="mt-5 text-center text-xs text-emerald-700">Livre</p>}</div>})}</div></article>)}</section>;
}

function NewReservation({resources,onClose,onSaved}:{resources:Resource[];onClose:()=>void;onSaved:()=>Promise<void>}){
 const [resource,setResource]=useState(resources[0]?.id??"");const [date,setDate]=useState(new Date().toLocaleDateString("en-CA",{timeZone:"America/Sao_Paulo"}));const [start,setStart]=useState("08:00");const [end,setEnd]=useState("09:00");const [purpose,setPurpose]=useState("");const [recurring,setRecurring]=useState(false);const [occ,setOcc]=useState("2");const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError("");try{const {error}=await supabase.rpc("criar_reservas",{_recurso_id:resource,_inicio:isoLocal(date,start),_fim:isoLocal(date,end),_finalidade:purpose,_ocorrencias:recurring?Number(occ):1});if(error)throw error;await onSaved();}catch(e){setError(e instanceof Error?e.message:"Não foi possível criar a reserva.");}finally{setSaving(false);}};
 return <form onSubmit={submit} className="space-y-4 rounded-2xl border bg-card p-4"><div className="flex items-center justify-between"><h2 className="font-bold">Nova reserva</h2><Button type="button" variant="ghost" onClick={onClose}>Fechar</Button></div><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-1.5 text-sm font-semibold">Recurso<select required className="h-10 w-full rounded-lg border bg-background px-3 font-normal" value={resource} onChange={e=>setResource(e.target.value)}>{resources.map(r=><option key={r.id} value={r.id}>{r.nome} — {categoryLabel(r.categoria)}</option>)}</select></label><label className="space-y-1.5 text-sm font-semibold">Data<input required type="date" className="h-10 w-full rounded-lg border bg-background px-3 font-normal" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="space-y-1.5 text-sm font-semibold">Início<select required className="h-10 w-full rounded-lg border bg-background px-3 font-normal" value={start} onChange={e=>setStart(e.target.value)}>{timeOptions()}</select></label><label className="space-y-1.5 text-sm font-semibold">Fim<select required className="h-10 w-full rounded-lg border bg-background px-3 font-normal" value={end} onChange={e=>setEnd(e.target.value)}>{timeOptions()}</select></label></div><label className="space-y-1.5 text-sm font-semibold block">Finalidade<textarea required minLength={3} maxLength={500} className="min-h-24 w-full rounded-lg border bg-background p-3 font-normal" value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={recurring} onChange={e=>setRecurring(e.target.checked)}/> Repetir semanalmente</label>{recurring?<label className="space-y-1.5 text-sm font-semibold block">Ocorrências<select className="h-10 w-full rounded-lg border bg-background px-3 font-normal" value={occ} onChange={e=>setOcc(e.target.value)}><option value="2">2 semanas</option><option value="3">3 semanas</option><option value="4">4 semanas</option></select></label>:null}{error?<p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>:null}<div className="flex gap-2"><Button type="submit" disabled={saving||!resource}>{saving?"Reservando…":"Reservar"}</Button><Button type="button" variant="outline" onClick={onClose}>Cancelar</Button></div></form>;
}

function timeOptions(){return Array.from({length:25},(_,i)=>{const total=7*60+i*30;const h=Math.floor(total/60),m=total%60;const v=String(h).padStart(2,"0")+":"+String(m).padStart(2,"0");return <option key={v} value={v}>{v}</option>});}

function ResourceManager({resources,onClose,onChanged}:{resources:Resource[];onClose:()=>void;onChanged:()=>Promise<unknown>}){
 const [name,setName]=useState("");const [category,setCategory]=useState<Category>("espaco");const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 async function add(){setSaving(true);setError("");try{const {error}=await supabase.from("recursos_reserva").insert({nome:name.trim(),categoria:category});if(error)throw error;setName("");await onChanged();}catch(e){setError(e instanceof Error?e.message:"Não foi possível cadastrar.");}finally{setSaving(false);}}
 async function toggle(r:Resource){const {error}=await supabase.from("recursos_reserva").update({ativo:!r.ativo}).eq("id",r.id);if(error)throw error;await onChanged();}
 return <section className="space-y-4 rounded-2xl border bg-card p-4"><div className="flex items-center justify-between"><div><h2 className="font-bold">Recursos</h2><p className="text-xs text-muted-foreground">Cadastre espaços e equipamentos.</p></div><Button variant="ghost" onClick={onClose}>Fechar</Button></div><div className="grid gap-2 sm:grid-cols-[1fr_180px_auto]"><input className="h-10 rounded-lg border bg-background px-3" placeholder="Ex.: Projetor 01" value={name} onChange={e=>setName(e.target.value)}/><select className="h-10 rounded-lg border bg-background px-3" value={category} onChange={e=>setCategory(e.target.value as Category)}><option value="espaco">Espaço</option><option value="equipamento">Equipamento</option></select><Button onClick={add} disabled={saving||name.trim().length<2}><Plus className="size-4"/>Cadastrar</Button></div>{error?<p role="alert" className="text-sm text-destructive">{error}</p>:null}<div className="grid gap-2 sm:grid-cols-2">{resources.map(r=><div key={r.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div><p className="font-semibold">{r.nome}</p><p className="text-xs text-muted-foreground">{categoryLabel(r.categoria)}</p></div><Button size="sm" variant="outline" onClick={()=>void toggle(r)}>{r.ativo?"Desativar":"Ativar"}</Button></div>)}</div></section>;
}
