/* eslint-disable */

// @ts-nocheck

// This file is automatically generated by TanStack Router.
// It is kept in sync with the route files in src/routes.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as HomeRouteImport } from './routes/_authenticated/home'
import { Route as ChamadosRouteImport } from './routes/_authenticated/chamados'
import { Route as AdminPessoasRouteImport } from './routes/_authenticated/admin/pessoas'
import { Route as AdminSetoresRouteImport } from './routes/_authenticated/admin/setores'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({ id: '/_authenticated', getParentRoute: () => rootRouteImport } as any)
const HomeRoute = HomeRouteImport.update({ id: '/_authenticated/home', path: '/home', getParentRoute: () => AuthenticatedRoute } as any)
const ChamadosRoute = ChamadosRouteImport.update({ id: '/_authenticated/chamados', path: '/chamados', getParentRoute: () => AuthenticatedRoute } as any)
const AdminPessoasRoute = AdminPessoasRouteImport.update({ id: '/_authenticated/admin/pessoas', path: '/admin/pessoas', getParentRoute: () => AuthenticatedRoute } as any)
const AdminSetoresRoute = AdminSetoresRouteImport.update({ id: '/_authenticated/admin/setores', path: '/admin/setores', getParentRoute: () => AuthenticatedRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/chamados': typeof ChamadosRoute
  '/admin/pessoas': typeof AdminPessoasRoute
  '/admin/setores': typeof AdminSetoresRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/_authenticated/home': typeof HomeRoute
  '/_authenticated/chamados': typeof ChamadosRoute
  '/_authenticated/admin/pessoas': typeof AdminPessoasRoute
  '/_authenticated/admin/setores': typeof AdminSetoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated': { id: '/_authenticated'; path: ''; fullPath: ''; preLoaderRoute: typeof AuthenticatedRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated/home': { id: '/_authenticated/home'; path: '/home'; fullPath: '/home'; preLoaderRoute: typeof HomeRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/chamados': { id: '/_authenticated/chamados'; path: '/chamados'; fullPath: '/chamados'; preLoaderRoute: typeof ChamadosRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/admin/pessoas': { id: '/_authenticated/admin/pessoas'; path: '/admin/pessoas'; fullPath: '/admin/pessoas'; preLoaderRoute: typeof AdminPessoasRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/admin/setores': { id: '/_authenticated/admin/setores'; path: '/admin/setores'; fullPath: '/admin/setores'; preLoaderRoute: typeof AdminSetoresRouteImport; parentRoute: typeof AuthenticatedRoute }
  }
}
const authenticatedChildren = {
  HomeRoute,
  ChamadosRoute,
  AdminPessoasRoute,
  AdminSetoresRoute,
}
const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(authenticatedChildren)
export interface AuthenticatedRouteChildren {
  HomeRoute: typeof HomeRoute
  ChamadosRoute: typeof ChamadosRoute
  AdminPessoasRoute: typeof AdminPessoasRoute
  AdminSetoresRoute: typeof AdminSetoresRoute
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}
const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AuthRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
